### ISSUE TITLE
missing 'tr_k' parameter in cluster_config in step 4. clustering.py 

### ISSUE THREAD

**Issue by almog-gueta** [nandinisa/CANarEx#1]
Hello, 

In `textrank_clustering() -> cluster() ->textrank_clustering.py ->  4. clustering.py `  there is a use of the parameter` cluster_config['tr_k']` (line 64). 
However, this parameter is not found in `cluster_config `which is in `cluster_config.py`, and not anywhere else in the project. 

This missing parameter cases a KeyError which terminates the run. 
What value should this parameter hold? 

Thank you!

**Comment by nandinisa** [comment]
Fixed the missing key in `cluster_config.py` commit `#0da5333`
